version: '2'
services:
  pg:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_PASSWORD: SuperSecure

  conjur:
    image: cyberark/conjur:latest
    command: server -a dev -f /work/conjur.yml
    environment:
      DATABASE_URL: postgres://postgres:SuperSecure@pg/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
      RAILS_ENV: development
    ports:
      - 80
    volumes:
      - .:/work
    depends_on:
      - pg

  client:
    image: cyberark/conjur-cli:5
    depends_on:
      - conjur
    entrypoint: /bin/bash
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_AUTHN_API_KEY:

  app:
    image: registry.tld/conjur-spring-boot-plugin
    depends_on:
      - conjur
      - client

  